icon: 'fas fa-microchip'
property: 'SoftwareApplication'
field:
  author:
    property: 'author'
  developer:
    property: 'creator'
  release-date:
    property: 'datePublished'
  language:
    property: 'inLanguage'
  programming-language:
    property: ''
  operating-system:
    property: 'operatingSystem'
  url:
    property: 'url'
  status:
    property: ''
  platform:
    property: ''
  size:
    property: 'fileSize'
  license:
    property: 'license'
  version:
    property: 'softwareVersion'
  category:
    property: 'applicationCategory'
